### PR TITLE
Support FA 4.3.0

### PR DESCRIPTION
**Pull request by cpg**
Note: I do not *really* know what I am doing. I just added files, paths, etc. following a pattern of what I saw.

That said, it "works for me" and I can see the new 4.3.0 icons working in my project.

### CODE REVIEW

**Comment by gabriel-dehan** [comment]
:+1:

**Comment by jbajou** [comment]
+1

**Comment by itsmrwave** [comment]
:+1: Would be great if this can get merged in ... if it's OK.

**Comment by supercodepoet** [comment]
Just updated the gem to 4.5.0

**Pull request closed without merging**
